### ISSUE TITLE
请问下右边的菜单栏可不可以做成隐藏

### ISSUE THREAD

**Issue by Chihono** [Gandum2077/JSEhViewer#2]
能不能就像yealico那样阅读的时候图片是全屏的，点击中间才唤出菜单呢？

**Comment by Gandum2077** [comment]
就是这么设计的，以便充分利用iPad空间

提示一下：绝大多数漫画都是按照A4纸规格出版，即1.414:1，而iPad尺寸为4:3，因此会有57px是用不上的，边栏就是处于这个位置

**Comment by Chihono** [comment]
哈哈这样啊，我这边是pro11寸2:3，全屏的显示视觉效果会更好一点，这个可以自己修改成隐藏吗

**Comment by Chihono** [comment]
> 就是这么设计的，以便充分利用iPad空间
> 
> 提示一下：绝大多数漫画都是按照A4纸规格出版，即1.414:1，而iPad尺寸为4:3，因此会有57px是用不上的，边栏就是处于这个位置

哈哈这样啊，我这边是pro11寸比例2388*1688，全屏的显示直接近似铺满图片了，视觉效果会更好一点，方便做11寸隐藏菜单的版本吗
![IMG_0005](https://user-images.githubusercontent.com/62991993/78341779-cfe5aa00-75ca-11ea-9ebb-539259303187.PNG)
![IMG_0006](https://user-images.githubusercontent.com/62991993/78341788-d2e09a80-75ca-11ea-9125-4056d9c974cb.PNG)

**Comment by Gandum2077** [comment]
隐藏边栏是肯定不会考虑的，因为这样做和这个应用的Feature冲突，此应用第一条Feature就是解放左手右手，因此一切需要多点一下的操作均不考虑，尤其是看图的时候（你想想这个应用为什么不使用滑动翻页？）  
至于你展示的第一张图片，根本就没有放在安全区域内。你把图片放在安全区域内，一样会有不少横向空间用不到。

补充一下，布局是不会考虑延伸到安全区域外的，这是为以后的通用版本做准备。

**Comment by Chihono** [comment]
> 隐藏边栏是肯定不会考虑的，因为这样做和这个应用的Feature冲突，此应用第一条Feature就是解放左手右手，因此一切需要多点一下的操作均不考虑，尤其是看图的时候（你想想这个应用为什么不使用滑动翻页？）
> 至于你展示的第一张图片，根本就没有放在安全区域内。你把图片放在安全区域内，一样会有不少横向空间用不到。
> 
> 补充一下，布局是不会考虑延伸到安全区域外的，这是为以后的通用版本做准备。

这样啊，主要是yealico的全屏阅读会比较舒服，jsehviewer的缓存和管理又比较好，所以觉着如果能在菜单栏里加个全屏按钮就好了

**Comment by Gandum2077** [comment]
不会。你这个机型太小众了，而且我也不打算适配我不用的机型，兼容就行了。
