### ISSUE TITLE
表象：卡在请等待界面

### ISSUE THREAD

**Issue by yyuueexxiinngg** [Gandum2077/JSEhViewer#6]
eh规则可能有所变更？目前发现：
- `uploader`可能变为`(Disowned)`，无指向上传者的链接，导致列表无法解析，卡在请等待。
复现：搜索`(C91) [Athome Shuka (Takunomi)] Enjo Kouhai [Chinese]`，或将其添加到fav后点击fav。且首页新上传的画廊有几率同样出现此现象导致无法加载。
- 画廊Tag可能为空导致无法解析infos，卡在请等待。不稳定复现：此上传者[KEYLUN](https://exhentai.org/uploader/KEYLUN/)中应该能找到Tag为空的画廊。

临时解决：https://github.com/Gandum2077/JSEhViewer/compare/master...yyuueexxiinngg:master

**Comment by errorfg** [comment]
目前ex更新，取消了页面数，导致无法翻页, 只能识别到1页

**Comment by Gandum2077** [comment]
此项目当年写的时候，iOS设备性能不够网页浏览太卡，才需要这个。现在性能上来了，我建议你用Safari扩展网页浏览。
