### ISSUE TITLE
收藏画廊过多时无法打开收藏界面

### ISSUE THREAD

**Issue by errorfg** [Gandum2077/JSEhViewer#7]
第一次打开时可以正常显示并且获取了收藏状况
![IMG_33491F13C25D-1](https://user-images.githubusercontent.com/18473413/151960934-9a631c79-0cdc-4470-876e-eb67afbeb02d.jpeg)
在收藏添加为下图的状态时, 再次打开收藏界面会卡死在请等待.
![CleanShot 2022-02-01 at 19 30 28@2x](https://user-images.githubusercontent.com/18473413/151961102-0df1d3ba-ce34-4bc7-9b1b-3a4303f54602.png)
如图
![IMG_9B6AECDDBB9D-1](https://user-images.githubusercontent.com/18473413/151961230-dc6f1bbd-0d11-4e96-9d75-f231736a646b.jpeg)

**Comment by yyuueexxiinngg** [comment]
试下fork [https://github.com/yyuueexxiinngg/JSEhViewer](https://github.com/yyuueexxiinngg/JSEhViewer)
会不会是因为收藏里包含了 #6 中的情况

**Comment by errorfg** [comment]
确实，好起来了
